master_activity_tasks = {
    # ✨ Creativity
    "Origami": [
        {"name": "Heart", "exp": 50},
        {"name": "Crane", "exp": 75},
        {"name": "Butterfly", "exp": 100},
        {"name": "Jumping Frog", "exp": 125},
        {"name": "Tulip", "exp": 150},
        {"name": "Flapping Bird", "exp": 175},
        {"name": "Samurai Helmet", "exp": 200},
        {"name": "Water Bomb", "exp": 225},
        {"name": "Dragon", "exp": 250},
        {"name": "Koi Fish", "exp": 275}
    ],
    "Painting": [
        {"name": "Still Life Sketch", "exp": 40},
        {"name": "Color Theory Exercise", "exp": 60},
        {"name": "Watercolor Practice", "exp": 80},
        {"name": "Perspective Drawing", "exp": 100},
        {"name": "Portrait Study", "exp": 120},
        {"name": "Abstract Piece", "exp": 140},
        {"name": "Oil Painting Basics", "exp": 160},
        {"name": "Landscape Scene", "exp": 180},
        {"name": "Night Sky Painting", "exp": 200},
        {"name": "Master Study", "exp": 250}
    ],
    "Pastel": [
        {"name": "Simple Shapes", "exp": 30},
        {"name": "Color Layering", "exp": 50},
        {"name": "Sunset Scene", "exp": 70},
        {"name": "Fruit Still Life", "exp": 90},
        {"name": "Texture Study", "exp": 110},
        {"name": "Animal Portrait", "exp": 130},
        {"name": "Abstract Design", "exp": 150},
        {"name": "Scenery Practice", "exp": 170},
        {"name": "Lighting Focus", "exp": 190},
        {"name": "Final Original Work", "exp": 230}
    ],
    "DigitalArt": [
        {"name": "Basic Brush Practice", "exp": 50},
        {"name": "Character Sketch", "exp": 70},
        {"name": "Coloring Practice", "exp": 90},
        {"name": "Simple Backgrounds", "exp": 110},
        {"name": "Dynamic Poses", "exp": 130},
        {"name": "Portrait Painting", "exp": 150},
        {"name": "Full Scene Sketch", "exp": 170},
        {"name": "Lighting & Shadows", "exp": 190},
        {"name": "Line Art Refinement", "exp": 210},
        {"name": "Original Full Artwork", "exp": 260}
    ],
    "Sketching": [
        {"name": "Basic Lines", "exp": 20},
        {"name": "Simple Objects", "exp": 40},
        {"name": "Human Figures", "exp": 60},
        {"name": "Perspective Drawing", "exp": 80},
        {"name": "Shading Practice", "exp": 100},
        {"name": "Face Studies", "exp": 120},
        {"name": "Gesture Drawing", "exp": 140},
        {"name": "Background Sketch", "exp": 160},
        {"name": "Dynamic Scenes", "exp": 180},
        {"name": "Original Composition", "exp": 220}
    ],
    "GraphicDesign": [
        {"name": "Typography Practice", "exp": 50},
        {"name": "Simple Poster", "exp": 70},
        {"name": "Color Scheme Practice", "exp": 90},
        {"name": "Logo Sketch", "exp": 110},
        {"name": "Minimalist Design", "exp": 130},
        {"name": "Infographic", "exp": 150},
        {"name": "Layout Challenge", "exp": 170},
        {"name": "Social Media Post", "exp": 190},
        {"name": "Ad Campaign Design", "exp": 210},
        {"name": "Portfolio Piece", "exp": 270}
    ],
    "Baking": [
        {"name": "Simple Cookies", "exp": 30},
        {"name": "Muffins", "exp": 50},
        {"name": "Bread Rolls", "exp": 70},
        {"name": "Cupcakes", "exp": 90},
        {"name": "Decorated Cake", "exp": 110},
        {"name": "Pie Baking", "exp": 130},
        {"name": "Layered Desserts", "exp": 150},
        {"name": "Themed Cookies", "exp": 170},
        {"name": "Artisan Bread", "exp": 190},
        {"name": "Custom Dessert Creation", "exp": 240}
    ],
    "Cooking": [
        {"name": "Simple Salad", "exp": 30},
        {"name": "Basic Pasta", "exp": 50},
        {"name": "Omelette", "exp": 70},
        {"name": "Simple Stir Fry", "exp": 90},
        {"name": "Grilled Dish", "exp": 110},
        {"name": "Baked Entree", "exp": 130},
        {"name": "Sauce Crafting", "exp": 150},
        {"name": "Meal Planning", "exp": 170},
        {"name": "Multi-course Meal", "exp": 190},
        {"name": "Signature Dish Creation", "exp": 240}
    ],
    "Photography": [
        {"name": "Rule of Thirds", "exp": 50},
        {"name": "Lighting Practice", "exp": 70},
        {"name": "Color Correction", "exp": 90},
        {"name": "Simple Portraits", "exp": 110},
        {"name": "Outdoor Scenes", "exp": 130},
        {"name": "Editing Basics", "exp": 150},
        {"name": "Perspective Shots", "exp": 170},
        {"name": "Night Photography", "exp": 190},
        {"name": "Full Series Project", "exp": 210},
        {"name": "Photo Essay Creation", "exp": 260}
    ],
    "Videography": [
        {"name": "Simple Video Clips", "exp": 50},
        {"name": "Cutting & Splicing", "exp": 70},
        {"name": "Basic Transitions", "exp": 90},
        {"name": "Audio Sync", "exp": 110},
        {"name": "Simple Effects", "exp": 130},
        {"name": "Short Video Project", "exp": 150},
        {"name": "Color Grading", "exp": 170},
        {"name": "Cinematic Shots", "exp": 190},
        {"name": "Mini Documentary", "exp": 210},
        {"name": "Final Film Project", "exp": 260}
    ],
    "Collage": [
        {"name": "Simple Shapes", "exp": 30},
        {"name": "Color Play", "exp": 50},
        {"name": "Magazine Clippings", "exp": 70},
        {"name": "Theme Collage", "exp": 90},
        {"name": "Mood Board", "exp": 110},
        {"name": "Multi-material Collage", "exp": 130},
        {"name": "Mixed Media", "exp": 150},
        {"name": "Large Format Piece", "exp": 170},
        {"name": "Abstract Collage", "exp": 190},
        {"name": "Gallery-ready Piece", "exp": 240}
    ],
    "TextileArt": [
    {"name": "Simple Stitch Practice", "exp": 30},
    {"name": "Small Coaster", "exp": 50},
    {"name": "Basic Scarf", "exp": 70},
    {"name": "Simple Crochet Animal", "exp": 90},
    {"name": "Pattern Following", "exp": 110},
    {"name": "Multi-color Project", "exp": 130},
    {"name": "Mini Blanket", "exp": 150},
    {"name": "Clothing Piece", "exp": 170},
    {"name": "Complex Pattern Item", "exp": 190},
    {"name": "Personalized Embroidery Art", "exp": 240}
],
    "Accessories": [
    {"name": "Simple Bracelet", "exp": 30},
    {"name": "Necklace Creation", "exp": 50},
    {"name": "Earring Set", "exp": 70},
    {"name": "Ring Making", "exp": 90},
    {"name": "Multi-strand Bracelet", "exp": 110},
    {"name": "Themed Jewelry Set", "exp": 130},
    {"name": "Beading Techniques", "exp": 150},
    {"name": "Wire Wrapping", "exp": 170},
    {"name": "Custom Design Challenge", "exp": 190},
    {"name": "Showcase Set", "exp": 240}
],
    "Journaling": [
    {"name": "Daily Entry", "exp": 20},
    {"name": "Gratitude Page", "exp": 40},
    {"name": "Creative Story Entry", "exp": 60},
    {"name": "Memory Capture", "exp": 80},
    {"name": "Illustrated Page", "exp": 100},
    {"name": "Dream Journal", "exp": 120},
    {"name": "Mood Tracker", "exp": 140},
    {"name": "Bucket List Journal", "exp": 160},
    {"name": "Vision Board Page", "exp": 180},
    {"name": "Full Month Journal Challenge", "exp": 220}
],
    "Singing": [
    {"name": "Breathing Exercises", "exp": 40},
    {"name": "Simple Song Practice", "exp": 60},
    {"name": "Vocal Warmups", "exp": 80},
    {"name": "Singing with Piano", "exp": 100},
    {"name": "Expand Vocal Range", "exp": 120},
    {"name": "Perform a Cover", "exp": 140},
    {"name": "Experiment with Vibrato", "exp": 160},
    {"name": "Singing in Harmony", "exp": 180},
    {"name": "Record a Song", "exp": 200},
    {"name": "Perform Live/Recorded Showcase", "exp": 250}
],
    "Rapping": [
    {"name": "Simple Flow Practice", "exp": 40},
    {"name": "Write Short Verse", "exp": 60},
    {"name": "Freestyle 30 Seconds", "exp": 80},
    {"name": "Rap Challenge (Random Word)", "exp": 100},
    {"name": "Record a Verse", "exp": 120},
    {"name": "Internal Rhyme Practice", "exp": 140},
    {"name": "Speed Challenge", "exp": 160},
    {"name": "Freestyle 1 Min", "exp": 180},
    {"name": "Collaborative Rap", "exp": 200},
    {"name": "Original Rap Performance", "exp": 250}
],
    "Poetry": [
    {"name": "Write a Haiku", "exp": 30},
    {"name": "Free Verse Poem", "exp": 50},
    {"name": "Rhymed Couplet", "exp": 70},
    {"name": "Themed Poem (Seasons)", "exp": 90},
    {"name": "Narrative Poem", "exp": 110},
    {"name": "Sonnet Attempt", "exp": 130},
    {"name": "Spoken Word Piece", "exp": 150},
    {"name": "Poetry Anthology (3+ poems)", "exp": 170},
    {"name": "Performance Reading", "exp": 190},
    {"name": "Original Poem Collection", "exp": 230}
],
    "Gardening": [
    {"name": "Plant a Seed", "exp": 20},
    {"name": "Water Care Routine", "exp": 40},
    {"name": "Repot a Plant", "exp": 60},
    {"name": "Start Herb Garden", "exp": 80},
    {"name": "Basic Pruning", "exp": 100},
    {"name": "Identify 5 Plant Species", "exp": 120},
    {"name": "Create Garden Layout", "exp": 140},
    {"name": "Grow Flower Plant", "exp": 160},
    {"name": "Harvest Herbs/Vegetables", "exp": 180},
    {"name": "Showcase Mini Garden", "exp": 220}
],
    "Calligraphy": [
    {"name": "Simple Alphabet", "exp": 30},
    {"name": "Letter Connection", "exp": 50},
    {"name": "Word Formation", "exp": 70},
    {"name": "Phrase Writing", "exp": 90},
    {"name": "Themed Practice", "exp": 110},
    {"name": "Brush Pen Lettering", "exp": 130},
    {"name": "Layout Composition", "exp": 150},
    {"name": "Quote Poster", "exp": 170},
    {"name": "Script Style Practice", "exp": 190},
    {"name": "Portfolio Showcase", "exp": 230}
],
    "Beatboxing": [
    {"name": "Basic Sounds (Kick/Snare)", "exp": 30},
    {"name": "Simple Beat Pattern", "exp": 50},
    {"name": "Speed Challenge", "exp": 70},
    {"name": "Freestyle Beat", "exp": 90},
    {"name": "Bass Drop Practice", "exp": 110},
    {"name": "Double-time Practice", "exp": 130},
    {"name": "Battle Style Beat", "exp": 150},
    {"name": "Sound Effects", "exp": 170},
    {"name": "Beatbox Loop", "exp": 190},
    {"name": "Record Beatbox Track", "exp": 230}
],
    "Penbeat": [
    {"name": "Basic Tapping", "exp": 30},
    {"name": "2-sound Combo", "exp": 50},
    {"name": "Simple Rhythm", "exp": 70},
    {"name": "Fast Combo Practice", "exp": 90},
    {"name": "Table Track Creation", "exp": 110},
    {"name": "Double Beat Speed", "exp": 130},
    {"name": "Signature Beat Creation", "exp": 150},
    {"name": "Cover a Song Beat", "exp": 170},
    {"name": "Freestyle Penbeat", "exp": 190},
    {"name": "Record & Post Challenge", "exp": 230}
],
    "Songwriting": [
    {"name": "Write a Short Melody", "exp": 40},
    {"name": "Create 4 Line Lyrics", "exp": 60},
    {"name": "Compose a Verse", "exp": 80},
    {"name": "Add Simple Chords", "exp": 100},
    {"name": "Write a Chorus", "exp": 120},
    {"name": "Verse + Chorus Demo", "exp": 140},
    {"name": "Basic Recording", "exp": 160},
    {"name": "Arrange Full Song", "exp": 180},
    {"name": "Record Full Song", "exp": 200},
    {"name": "Song Release Project", "exp": 260}
],
    "CreativeWriting": [
    {"name": "Short Story (100 words)", "exp": 30},
    {"name": "Character Sketch", "exp": 50},
    {"name": "Setting Description", "exp": 70},
    {"name": "Dialogue Practice", "exp": 90},
    {"name": "Conflict Scene", "exp": 110},
    {"name": "First Chapter Draft", "exp": 130},
    {"name": "Plot Twist Scene", "exp": 150},
    {"name": "Short Story Complete", "exp": 170},
    {"name": "Full Short Story Series", "exp": 190},
    {"name": "Publish Online Challenge", "exp": 250}
],
"Drama": [
    {"name": "Simple Monologue", "exp": 40},
    {"name": "Mimic Scene Practice", "exp": 60},
    {"name": "Voice Projection Exercise", "exp": 80},
    {"name": "Emotional Scene", "exp": 100},
    {"name": "Dialogue Reenactment", "exp": 120},
    {"name": "Stage Presence Practice", "exp": 140},
    {"name": "Memorize 2-Minute Script", "exp": 160},
    {"name": "Perform to Audience", "exp": 180},
    {"name": "Video Monologue Recording", "exp": 200},
    {"name": "Acting Portfolio Project", "exp": 260}
],
"Juggling": [
    {"name": "Basic Toss Practice", "exp": 30},
    {"name": "Two-ball Cascade", "exp": 50},
    {"name": "Three-ball Cascade", "exp": 70},
    {"name": "Reverse Cascade", "exp": 90},
    {"name": "Column Pattern", "exp": 110},
    {"name": "Under the Leg", "exp": 130},
    {"name": "Mills Mess Beginner", "exp": 150},
    {"name": "Mills Mess Full Pattern", "exp": 170},
    {"name": "Five-ball Flash", "exp": 190},
    {"name": "Performance Routine", "exp": 230}
],
"RubixCubing": [
    {"name": "Solve One Face", "exp": 30},
    {"name": "Solve Cross (Beginner)", "exp": 50},
    {"name": "Solve Full Cube (Guide)", "exp": 70},
    {"name": "Beginner Method Practice", "exp": 90},
    {"name": "Learn F2L Basics", "exp": 110},
    {"name": "Learn 2-Look OLL", "exp": 130},
    {"name": "Learn 2-Look PLL", "exp": 150},
    {"name": "Full CFOP Solve", "exp": 170},
    {"name": "Sub-60 Second Solve", "exp": 190},
    {"name": "Sub-30 Second Solve", "exp": 230}
],
"MagicTricks": [
    {"name": "Basic Card Force", "exp": 30},
    {"name": "Simple Coin Vanish", "exp": 50},
    {"name": "Rubber Band Trick", "exp": 70},
    {"name": "Double Lift Practice", "exp": 90},
    {"name": "Self-Working Card Trick", "exp": 110},
    {"name": "Basic Sleight of Hand", "exp": 130},
    {"name": "Coin Through Table", "exp": 150},
    {"name": "Ambitious Card Routine", "exp": 170},
    {"name": "Card to Pocket Trick", "exp": 190},
    {"name": "Magic Routine Performance", "exp": 230}
],
"CardManipulation": [
    {"name": "One-Hand Cut", "exp": 30},
    {"name": "Charlier Cut", "exp": 50},
    {"name": "Thumb Fan", "exp": 70},
    {"name": "Pressure Fan", "exp": 90},
    {"name": "Card Spring Practice", "exp": 110},
    {"name": "Basic Card Flourish", "exp": 130},
    {"name": "Cardistry Combo", "exp": 150},
    {"name": "Sybil Cut", "exp": 170},
    {"name": "Smooth Packet Cut", "exp": 190},
    {"name": "Freestyle Cardistry Routine", "exp": 230}
],
"Coding": [
    {"name": "Print Hello World", "exp": 30},
    {"name": "Simple If/Else Program", "exp": 50},
    {"name": "Looping Practice", "exp": 70},
    {"name": "Basic Function", "exp": 90},
    {"name": "Simple Project (e.g., Calculator)", "exp": 110},
    {"name": "Intro to Classes", "exp": 130},
    {"name": "API Fetch Practice", "exp": 150},
    {"name": "Small Webpage", "exp": 170},
    {"name": "Mini Bot/App Project", "exp": 190},
    {"name": "Full Project Build", "exp": 250}
],
"Chess": [
    {"name": "Learn Piece Movement", "exp": 30},
    {"name": "Learn Basic Checkmates", "exp": 50},
    {"name": "Simple Opening Practice", "exp": 70},
    {"name": "Learn Pin, Fork, Skewer", "exp": 90},
    {"name": "Play 3 Practice Games", "exp": 110},
    {"name": "Analyze Own Game", "exp": 130},
    {"name": "Learn Opening Traps", "exp": 150},
    {"name": "Tactics Training", "exp": 170},
    {"name": "Beat 1200 Rated Bot", "exp": 190},
    {"name": "Win Tournament Game", "exp": 250}
],
"Cardio": [
    {"name": "5-Minute Jog", "exp": 30},
    {"name": "Jump Rope Practice", "exp": 50},
    {"name": "10-Minute Jog", "exp": 70},
    {"name": "Interval Running", "exp": 90},
    {"name": "20-Minute Cardio Session", "exp": 110},
    {"name": "Outdoor Sprint Practice", "exp": 130},
    {"name": "Cardio Circuit Workout", "exp": 150},
    {"name": "30-Minute Continuous Jog", "exp": 170},
    {"name": "Hill Sprint Challenge", "exp": 190},
    {"name": "5K Run Achievement", "exp": 240}
],
"Dance": [
    {"name": "Learn Basic Steps", "exp": 30},
    {"name": "1-Minute Routine Practice", "exp": 50},
    {"name": "Copy TikTok/Short Dance", "exp": 70},
    {"name": "Learn a Full Song Routine", "exp": 90},
    {"name": "Freestyle Practice", "exp": 110},
    {"name": "Dance Style Challenge (e.g. Salsa, Hip-Hop)", "exp": 130},
    {"name": "2-Minute Routine Practice", "exp": 150},
    {"name": "Small Group Dance Sync", "exp": 170},
    {"name": "Perform to an Audience (even online)", "exp": 190},
    {"name": "Record Dance Showcase", "exp": 240}
],
"HIIT": [
    {"name": "Simple Tabata Set", "exp": 30},
    {"name": "Full Body Beginner HIIT", "exp": 50},
    {"name": "Core-Focused HIIT", "exp": 70},
    {"name": "Legs & Glutes HIIT", "exp": 90},
    {"name": "HIIT Cardio Circuit", "exp": 110},
    {"name": "Power HIIT (Burpees, Mountain Climbers)", "exp": 130},
    {"name": "20-Minute HIIT Session", "exp": 150},
    {"name": "Custom HIIT Workout Build", "exp": 170},
    {"name": "Strength + Cardio HIIT", "exp": 190},
    {"name": "30-Minute Endurance HIIT Challenge", "exp": 250}
],
"Yoga": [
    {"name": "Simple Sun Salutation", "exp": 30},
    {"name": "5-Minute Stretching Routine", "exp": 50},
    {"name": "Beginner Yoga Flow", "exp": 70},
    {"name": "Breathing Exercises Practice", "exp": 90},
    {"name": "Balance Poses Challenge", "exp": 110},
    {"name": "Intermediate Yoga Sequence", "exp": 130},
    {"name": "Deep Stretch Session", "exp": 150},
    {"name": "Yoga for Relaxation Routine", "exp": 170},
    {"name": "Power Yoga Flow", "exp": 190},
    {"name": "30-Minute Complete Yoga Practice", "exp": 240}
],
"Frisbee": [
    {"name": "Basic Throw Practice", "exp": 30},
    {"name": "Catch & Throw Drills", "exp": 50},
    {"name": "Learn Forehand Throw", "exp": 70},
    {"name": "Master Backhand Throw", "exp": 90},
    {"name": "Target Throw Accuracy", "exp": 110},
    {"name": "Run and Catch Drills", "exp": 130},
    {"name": "Mini Frisbee Game (2v2)", "exp": 150},
    {"name": "Mid-Field Passing Practice", "exp": 170},
    {"name": "Scrimmage Game", "exp": 190},
    {"name": "Full Frisbee Match Play", "exp": 240}
],
"Boardgame": [
    {"name": "Learn Rules of New Board Game", "exp": 30},
    {"name": "Play One Game Session", "exp": 50},
    {"name": "Teach Rules to Another Person", "exp": 70},
    {"name": "Win a Match", "exp": 90},
    {"name": "Learn Advanced Strategies", "exp": 110},
    {"name": "Complete 3 Matches", "exp": 130},
    {"name": "Try Cooperative Mode (if available)", "exp": 150},
    {"name": "Host a Board Game Night", "exp": 170},
    {"name": "Win 3 Matches in a Row", "exp": 190},
    {"name": "Create House Rules Variant", "exp": 240}
],
"Shows": [
    {"name": "Pick a New Series or Movie", "exp": 30},
    {"name": "Watch 1st Episode or 30 Min", "exp": 50},
    {"name": "Analyze Character Introductions", "exp": 70},
    {"name": "Watch 3+ Episodes", "exp": 90},
    {"name": "Predict Storyline Plot Twists", "exp": 110},
    {"name": "Complete First Season (or Movie)", "exp": 130},
    {"name": "Write a Short Review", "exp": 150},
    {"name": "Recommend to a Friend", "exp": 170},
    {"name": "Start a Watch Party", "exp": 190},
    {"name": "Analyze Director’s Style", "exp": 240}
],
"Songs": [
    {"name": "Listen to 3 New Songs", "exp": 30},
    {"name": "Explore a New Genre", "exp": 50},
    {"name": "Create a New Playlist", "exp": 70},
    {"name": "Recommend a Song to a Friend", "exp": 90},
    {"name": "Discover 5 New Artists", "exp": 110},
    {"name": "Create Genre-Specific Playlist", "exp": 130},
    {"name": "Learn the Lyrics of a New Song", "exp": 150},
    {"name": "Cover a Song", "exp": 170},
    {"name": "Create a Collaborative Playlist", "exp": 190},
    {"name": "Host a Music Sharing Session", "exp": 240}
],
"Language": [
    {"name": "Learn 5 Basic Words", "exp": 30},
    {"name": "Practice Basic Greetings", "exp": 50},
    {"name": "Learn Days of the Week", "exp": 70},
    {"name": "Memorize 10 Vocabulary Words", "exp": 90},
    {"name": "Form Simple Sentences", "exp": 110},
    {"name": "Listen to a Beginner Dialogue", "exp": 130},
    {"name": "Hold a Basic Conversation", "exp": 150},
    {"name": "Watch a Short Video in Target Language", "exp": 170},
    {"name": "Write a Short Paragraph", "exp": 190},
    {"name": "Complete a Language App Level (Duolingo, Memrise)", "exp": 240}
],
"WikipediaMarathon": [
    {"name": "Read 1 Random Wikipedia Article", "exp": 30},
    {"name": "Follow 2 Article Links", "exp": 50},
    {"name": "Reach a Completely Different Topic", "exp": 70},
    {"name": "Record Fun Facts Discovered", "exp": 90},
    {"name": "Marathon 5 Articles in a Row", "exp": 110},
    {"name": "Start from a Random Start and Set a Final Target", "exp": 130},
    {"name": "Reach Target in Under 10 Links", "exp": 150},
    {"name": "Challenge Friend to Wikipedia Race", "exp": 170},
    {"name": "Write a Summary of What You Learned", "exp": 190},
    {"name": "Complete a Full 30-Minute Marathon Session", "exp": 240}
],
"MorseCode": [
    {"name": "Learn SOS in Morse Code", "exp": 30},
    {"name": "Learn A–E Letters in Morse", "exp": 50},
    {"name": "Translate a Word into Morse Code", "exp": 70},
    {"name": "Tap Out Basic Word (like 'HI')", "exp": 90},
    {"name": "Learn Numbers 0–9", "exp": 110},
    {"name": "Practice 10 Common Words", "exp": 130},
    {"name": "Translate a Short Message", "exp": 150},
    {"name": "Send a Morse Message to a Friend", "exp": 170},
    {"name": "Decode a Morse Puzzle", "exp": 190},
    {"name": "Master Full Alphabet Practice", "exp": 240}
],
"SignLanguage": [
    {"name": "Learn Hello and Thank You", "exp": 30},
    {"name": "Learn How to Introduce Yourself", "exp": 50},
    {"name": "Master the Alphabet A–E", "exp": 70},
    {"name": "Fingerspell Your Name", "exp": 90},
    {"name": "Learn Family Signs (Mother, Father)", "exp": 110},
    {"name": "Learn Emotions Signs (Happy, Sad)", "exp": 130},
    {"name": "Hold Simple Signed Conversation", "exp": 150},
    {"name": "Watch Beginner ASL/LSQ Video", "exp": 170},
    {"name": "Sign Full Sentences", "exp": 190},
    {"name": "Perform a Short Signed Story", "exp": 240}
],
"NewBook": [
    {"name": "Select a New Book to Start", "exp": 30},
    {"name": "Read First Chapter", "exp": 50},
    {"name": "Write 3-5 Sentence Summary", "exp": 70},
    {"name": "Reach 25% Progress", "exp": 90},
    {"name": "Identify Main Characters", "exp": 110},
    {"name": "Predict Story Ending", "exp": 130},
    {"name": "Reach 50% Progress", "exp": 150},
    {"name": "Reflect on Major Themes", "exp": 170},
    {"name": "Finish the Book", "exp": 190},
    {"name": "Write a Full Book Review", "exp": 250}
],

}

